# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: MS Test
      run: dotnet test -l:trx;LogFileName=TestOutput.xml --no-build --verbosity normal
      working-directory: src/UnitTestProject

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()      
      with:
        files: |
          src/UnitTestProject/*.trx
          # test-results/**/*.xml
          # test-results/**/*.trx
          # test-results/**/*.json
  
